#!/bin/sh
#
# $1: interface name used by pppd (e.g. ppp3)
# $2: tty device name
# $3: tty device speed
# $4: local IP address for the interface
# $5: remote IP address
# $6: parameter specified by the 'ipparam' option to pppd
#

#rm -f /tmp/resolv.conf
#mv /tmp/resolv.bak /tmp/resolv.conf
rm -f /etc/resolv.ppp

exit 0
