#!/bin/sh
#
# $1: interface name used by pppd (e.g. ppp3)
# $2: tty device name
# $3: tty device speed
# $4: local IP address for the interface
# $5: remote IP address
# $6: parameter specified by the 'ipparam' option to pppd
#

if (test "10.11.12.13" = "$DNS1") then
  echo "nameserver 8.8.8.8" > /etc/resolv.ppp
fi

if (test "10.11.12.14" = "$DNS2") then
  echo "nameserver 8.8.4.4" >> /etc/resolv.ppp
fi

if (test -f "/etc/resolv.conf")
then
  echo "file exists skip"
else
  cp /etc/resolv.ppp /etc/resolv.conf
fi

networkcfgfile="/etc/sysconfig/network.cfg"

echo "mobile_network_ip_addr: $4" > /tmp/$1.info

# ppp interface IP route 1
awk '
{
	split ($0, x, "=");

	if (dev ".gw0.addr" == x[1] && "" != x[2])
		gw0_addr = ("0.0.0.0" == x[2]) ? gw : x[2];
	else if (dev ".gw0.metric" == x[1] && "" != x[2])
		gw0_metric = x[2];
}
END
{
	if ("" != gw0_addr && "" != gw0_metric)
		system ("route add default gw " gw0_addr " metric " gw0_metric);
}
' -v dev=$1 -v gw=$5 $networkcfgfile

exit 0
