#!/bin/sh

# Copyright (C) 2012 WenJing <wenjing0101@gmail.com>
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

START_LOG_FILE="/tmp/startup.log"
export START_LOG_FILE

for i in /etc/init.d/S??_* ;do
        $i
done
