#!/bin/sh

if [ `gpio R C 4` -eq 0 ] && [ `gpio R C 5` -eq 0 ];then
    rm /etc/passwd /etc/group /etc/shadow /etc/sysconfig -rf
    ln -s /etc/.sysconfig/passwd /etc/passwd 
    ln -s /etc/.sysconfig/group /etc/group 
    ln -s /etc/.sysconfig/shadow /etc/shadow 
    ln -s /etc/.sysconfig /etc/sysconfig
    exit 0
fi

if (! test -f /info/passwd || ! test -f /info/group || ! test -f /info/shadow)
then
    unlock info
    mv /etc/.sysconfig/passwd /info/passwd
    mv /etc/.sysconfig/group /info/group
    mv /etc/.sysconfig/shadow /info/shadow
    lock info
fi

if (! test -d /info/sysconfig)
then
    unlock info
    mv /etc/.sysconfig /info/sysconfig
    lock info
fi

