#!/bin/sh

#
# Rules
#
# RTC work? -----Y----> RTC Newer Than Saved_Time? ----Y----> exit(0)
#           \                                      \
#            \                                      ---N----> Use Saved_Time
#             ---N----> Use Saved_Time 
#

LAST_FILE="/etc/sysconfig/TIME"
NEW_FILE="/tmp/.empty"

touch $NEW_FILE

/sbin/hwclock

if [ 0 -eq $? ];then

    if [ ${NEW_FILE} -ot ${LAST_FILE} ];then
        echo -e "\n[WARN      ] : $0 Detected RTC slower than the default ${LAST_FILE}\n" >> ${START_LOG_FILE}
    else
        exit 0
    fi

else
    echo -e "\n[ERROR     ] : $0 Cannot read RTC HARDWARE\n" >> ${START_LOG_FILE}
fi

##################################################################
# We use Last store time as startup time
##################################################################
LAST_TIME=`cat ${LAST_FILE}`

date -s ${LAST_TIME}
hwclock -uw ### Maybe failed if the hardeare initialization failed

