#!/bin/sh

NTPSERVER_IP=""
EEPROM="/sys/devices/platform/i2c-gpio/i2c-0/0-0050/eeprom"

ntpServer_check() 
{
    sleep 1 

    echo `ifconfig eth0 | grep "inet addr"` >> ${START_LOG_FILE} 

    if [ 1 -eq `ping -c 1 -s 64 -W 1 -w 1 -q 192.168.200.188 | grep "received, 0%" | wc -l` ];then
        NTPSERVER_IP="192.168.200.188"
    elif [ 1 -eq `ping -c 1 -s 64 -W 1 -w 1 -q 192.168.9.188 | grep "received, 0%" | wc -l` ];then
        NTPSERVER_IP="192.168.9.188"
    fi

    if [ -n "${NTPSERVER_IP}" ];then

        sntpdate ${NTPSERVER_IP}

        if [ 0 -eq $? ];then
            echo -e "\n[INFO      ] : $0 Sync with ntpserver from ${NTPSERVER_IP} Success\n" >> ${START_LOG_FILE}
            hwclock -uw
        else
            echo -e "\n[ERROR     ] : $0 Sync with ntpserver from ${NTPSERVER_IP} Failed\n" >> ${START_LOG_FILE}
        fi

        tftp -gr `ifconfig eth0 | grep HWaddr| awk '{print $5}'` ${NTPSERVER_IP}

    else
        echo -e "\n[ERROR     ] : $0 Cannot connect both ntpserver, please check your network\n" >> ${START_LOG_FILE}
    fi
}


# =====================
# | Default Parameters
# =====================

    env_awk="/etc/init.d/env.awk"
    network_cfg="/etc/sysconfig/network.cfg"
    DEFAULT_IPADDR="192.168.200.200"

    # All the default static ip and routing
    ifconfig lo 127.0.0.1 up
    route add -net 127.0.0.0 netmask 255.0.0.0 lo

    cat ${EEPROM} | grep "MAC"

    if [ 0 -eq $? ];then
        MAC=`cat ${EEPROM} | grep "MAC" | awk -F'=' '{print $2}'`
    else
        MAC_P1=`awk -F'[=M]' '{print int($2/100)":"$2%100}' /etc/fs.fcfg`
        MAC_P2=`date -u +%m:%d:%H`
        MAC_P0=0

        grep -q "M$" /etc/fs.fcfg

        if [ 0 -eq $? ];then 
            MAC_P0=EE
        fi
        MAC=${MAC_P0}:${MAC_P1}:${MAC_P2}
    fi

    ifconfig eth0 down && ifconfig eth0 hw ether ${MAC}

    # If it's boot from NFS or network configure file doesn't exist, then use default IP address. 
    dmesg | grep "Mounted root (nfs filesystem)"
    if [ 0 -eq $? -o ! -f $network_cfg ]
    then 

        echo -e "\n[WARN      ] : $0 Will set Default IP ADDR as ${DEFAULT_IPADDR}\n" >> ${START_LOG_FILE}
        ifconfig eth0 ${DEFAULT_IPADDR} netmask 255.255.255.0 up 
        ntpServer_check
        exit 0
    fi 

# =================
# | User parameter
# =================
    ifname=eth0

    if [ $# -ne 0 ]
    then
        ifname=$1
    fi

    if [ $ifname != "all" -a $ifname != "eth0" ]
    then
        # ========
        # | Usage
        # ========

        echo "Invalid interface name [ $1 ]"
        echo ""
        echo "Valid interface name : eth0, all"

        exit 1
    fi

# ================
# | Setup network
# ================

    rm /etc/resolv.conf

# ==========================================================
# == eth0 interface MAC address and dhcp                  ==
# ==========================================================

    awk -v ifname=$ifname -f $env_awk $network_cfg  
    ntpServer_check
    exit 0

