/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 249M$
 * $Date: 2011-12-24$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		249
#define SVN_REVSTR	"249M"
#define SVN_REVDATE	"2011-12-24"
#define SVN_REVSTAMP	20111224L
#define SVN_REVMODIFIED	1

#endif /* SVN_REV_H */
