
OBJS := terminfo.o uplink_buffer.o uplink_dl.o svrmsg.o ethsvr.o keepalive.o svrcomm.o ether.o ctrlcmd.o \
		serial.o tranfile.o ir.o cascade.o
SUBDIR := ppp gprs
#SYMBOLOUT := dir1_script.txt

-include $(SUBMK_FILE)

