#!/bin/sh
#

crondflag=$1

networkcfgfile="/etc/sysconfig/network.cfg"
inspect_addr=`awk '
	{
		split ($0, x, "=");

		if ("ntpd.inspect.addr" == x[1] && "" != x[2])
		{
			printf ("%s", x[2]);
			exit 0;
		}	
	}
	' $networkcfgfile`

primary_addr=`awk '
	{
		split ($0, x, "=");

		if ("ntpd.primary.addr" == x[1] && "" != x[2])
		{
			printf ("%s", x[2]);
			exit 0;
		}	
	}
	' $networkcfgfile`

secondary_addr=`awk '
	{
		split ($0, x, "=");

		if ("ntpd.secondary.addr" == x[1] && "" != x[2])
		{
			printf ("%s", x[2]);
			exit 0;
		}	
	}
	' $networkcfgfile`

# check is NTP inspection address set or not. if EMPTY do not update
if (test -n "$inspect_addr" && test -n "$primary_addr")
then
	while true;
	do
		if ((date | awk -F" " 'BEGIN{updated = 0;} END{if($6 >= 2012) updated = 1; exit updated}') || (test "1" == "$crondflag"))
		then
			#check if there is connection to the internet before updating the date
			if (ping -c 1 $inspect_addr)
			then
				# update date time with time server
				sntpdate $primary_addr
				if (sntpdate $primary_addr)
				then
					hwclock -wu
					exit 0
				elif (test -n "$secondary_addr")
				then
					# if the first primary time server is down then try the backup server
					if (sntpdate $secondary_addr)
					then
						hwclock -wu
						exit 0
					fi
				fi
			else
				sleep 1
			fi
		else
			exit 0
		fi
	done
fi

exit 0
