/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 13M$
 * $Date: 2011-12-16$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		13
#define SVN_REVSTR	"13M"
#define SVN_REVDATE	"2011-12-16"
#define SVN_REVSTAMP	20111216L
#define SVN_REVMODIFIED	1

#endif /* SVN_REV_H */
