#!/bin/sh
SERVER_IP="192.168.200.188"

if [ $# -ge 1 ];then

    FILE_NAME="$1"

else
    echo "USAGE : $0 FILE_NAME [?*]"
    exit

fi

tftp -gr $FILE_NAME $SERVER_IP && chmod 777 $FILE_NAME

KO=$(ls $FILE_NAME | awk -F'.' '{ print $2 }')
if [ $# -ge 2 -a "$KO" = "ko" ];then

    DRV_NAME=$(ls $FILE_NAME | awk -F'.' '{ print $1 }')

    DRV_STATUS=$(lsmod | grep "$DRV_NAME" | wc -l)

    if [ $DRV_STATUS = "1" ];then
        rmmod $DRV_NAME
    fi

    insmod $DRV_NAME.ko

fi
