#!/bin/sh

USAGE ()
{
    echo "USAGE : $0   CMD(R/W)   TYPE(A/B/C)   PIN(0-32)   [VALUE (0/1)]"
    echo "read  PA20   : $0 R A 20"
    echo "write PC12 1 : $0 W C 12 1"
    exit
}

if [ $2 = "A" ];then
        GPIO=`expr $3 + 32`
elif [ $2 = "B" ];then
        GPIO=`expr $3 + 64`
elif [ $2 = "C" ];then
        GPIO=`expr $3 + 96`
else
        USAGE;
fi

if [ $# -lt 3 ] || [ $# -gt 4 ] || [ $3 -gt 32 ];then
        USAGE;
fi

if [ $1 = "R" ];then

        if [ ! -d /sys/class/gpio/gpio${GPIO} ];then 
            echo ${GPIO} > /sys/class/gpio/export
        fi

        #if [ "out" = "`cat /sys/class/gpio/gpio${GPIO}/direction`" ];then
        #    echo "in" > /sys/class/gpio/gpio${GPIO}/direction
        #fi

        cat /sys/class/gpio/gpio${GPIO}/value

elif [ $1 = "W" ] && [ 4 -eq $# ];then

	if [ 1 -eq $4 ] || [ 0 -eq $4 ];then
	
        if [ ! -d /sys/class/gpio/gpio${GPIO} ];then 
            echo ${GPIO} > /sys/class/gpio/export
        fi

        if [ "in" = "`cat /sys/class/gpio/gpio${GPIO}/direction`" ];then
            echo "out" > /sys/class/gpio/gpio${GPIO}/direction
        fi
        
        echo $4 > /sys/class/gpio/gpio${GPIO}/value
        cat /sys/class/gpio/gpio${GPIO}/value
        
    else
	        USAGE;
    fi
else
        USAGE;
fi
