
OBJS := mdbcur.o mdbana.o dbconfig.o dbase.o mdbfrez.o mdbuene.o curve.o \
		mdbstic.o mdbsave.o cuvupdate.o mdbstat.o mdb.o dbclear.o sndtime.o \
		mdbtgrp.o
#SUBDIR := syscall
#SYMBOLOUT := dir1_script.txt

-include $(SUBMK_FILE)

