
test:
	gcc -D__TEST__ -Wall -o DSH4test bakEachRequest4OneCode.c
release:
	gcc -Wall -o DSH bakEachRequest4OneCode.c
	'cp' -av DSH /var/www/icons/DSH2
debug:
	gcc -D__TEST__ -D__DEBUG__ -Wall -o DSH4test bakEachRequest4OneCode.c
